---
- name: Install all programs
  hosts: all
  become: yes

  tasks:
  - name: Update apt packeage 
    become: true
    apt:
      update_cache: yes

  - name: Install required packages
    apt:
      name: ['apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']
      state: latest
      update_cache: yes



  - name: Add Docker GPG apt key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add Docker Repository
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu xenial stable
      state: present

  - name: Update apt and install docker-ce
    apt: update_cache=yes name=docker-ce state=latest

  - name: Install Docker Module for Python
    pip:
      name: docker



  - name: Adding existing users to group
    user:
      name: '{{ ansible_user }}'
      groups: docker
      append: yes

  - name: Configure ufw rules
    ufw: rule=allow port=80 proto=tcp

  - name: Enable ufw logging
    ufw: logging=on

  - name: Enable ufw
    ufw: state=enabled policy=allow



  - name: Restart Docker
    service: name=docker state=restarted

  - name: Get running containers
    docker_host_info:
      containers: yes
    register: docker_info

  - name: Stop running containers
    docker_container:
      name: "{{ item }}"
      state: stopped
    loop: "{{ docker_info.containers | map(attribute='Id') | list }}"
  
  - name: Create container
    docker_container:
      name: "mynginxContainerB"
      image: "taraszhygal/nginx-back-server"
      ports:
        - "80:80"